sudo: required
language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36,flake8,mypy,pydocstyle,docs,codecov

addons:
  chrome: stable

before_script:
  - wget https://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ${TRAVIS_BUILD_DIR}

install:
  - pip install tox

script:
  - tox
