language: python
python:
  - "3.5.1"

addons:
  apt:
    packages:
      - xvfb

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - pip install tornado aiohttp syncer
  - pip install pytest pytest-cov selenium
  - pip install codecov coveralls
script:
  - py.test --cov wdom
after_success:
  - echo $TRAVIS_BRANCH
  - codecov -b $TRAVIS_BRANCH
  - coveralls
