sudo: false
dist: trustry
language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36,flake8,mypy,pydocstyle,docs,codecov

addons:
  chrome: stable

install:
  - pip install tox

script:
  - tox
