sudo: false
dist: trusty
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

addons:
  apt:
    packages:
      - google-chrome-stable

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - wget https://chromedriver.storage.googleapis.com/2.29/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ${TRAVIS_BUILD_DIR}

install:
  - pip install selenium parameterized syncer coverage green
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4* ]]; then pip install mypy; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then pip install codecov coveralls; fi
  - pip install ${TRAVIS_BUILD_DIR}
script:
  - mkdir maint && cd maint
  - cp ${TRAVIS_BUILD_DIR}/.green ./
  - green -R ${TRAVIS_BUILD_DIR}
  - coverage report
  - cp .coverage ${TRAVIS_BUILD_DIR}
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then cd ${TRAVIS_BUILD_DIR} && codecov -b $TRAVIS_BRANCH && coveralls; fi
