sudo: false
dist: trusty
language: python
python:
  - "3.5"
  - "3.6"

addons:
  chrome: stable

before_script:
  - wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ${TRAVIS_BUILD_DIR}

install:
  - pip install -r requirements-test.txt
  - pip install coverage green
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then pip install pyppeteer codecov coveralls flake8 mypy; fi
  - pip install ${TRAVIS_BUILD_DIR}
script:
  - mkdir maint && cd maint
  - if [[ ! $TRAVIS_PYTHON_VERSION == 3.6* ]]; then green -c ../.green -s 1 ${TRAVIS_BUILD_DIR}/wdom/tests; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then green -c ../.green -s 1 -r ${TRAVIS_BUILD_DIR}/wdom/tests ${TRAVIS_BUILD_DIR}/tests_py36 && cp .coverage ${TRAVIS_BUILD_DIR}; fi
  - cd ${TRAVIS_BUILD_DIR}
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then flake8 setup.py wdom; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then mypy wdom; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then codecov -b $TRAVIS_BRANCH && coveralls; fi
