language: python
python:
  - "3.5.1"

addons:
  apt:
    packages:
      - xvfb

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - pip install tornado aiohttp syncer
  - pip install selenium coverage
  - pip install codecov coveralls
script:
  - coverage run --source wdom run_test.py
after_success:
  - codecov -b $TRAVIS_BRANCH
  - coveralls
