sudo: false
dist: trusty
language: python
python:
  - "3.5"
  - "3.6"

addons:
  chrome: stable

before_script:
  - wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ${TRAVIS_BUILD_DIR}

install:
  - pip install -r requirements-test.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then pip install coverage codecov flake8 mypy; fi
  - pip install ${TRAVIS_BUILD_DIR}
script:
  - mkdir maint && cd maint
  - if [[ ! $TRAVIS_PYTHON_VERSION == 3.6* ]]; then python -m unittest discover ${TRAVIS_BUILD_DIR}/tests; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then coverage run --rcfile=${TRAVIS_BUILD_DIR}/.coveragerc -m unittest discover ${TRAVIS_BUILD_DIR}/tests; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then coverage report && cp .coverage ${TRAVIS_BUILD_DIR}; fi
  - cd ${TRAVIS_BUILD_DIR}
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then flake8 setup.py wdom tests; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then mypy wdom; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6* ]]; then codecov -b $TRAVIS_BRANCH && coveralls; fi
