language: python
python:
  - "3.5"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
before_install:
  - "export CHROME_BIN=chromium-browser"
install:
  - pip install tornado pystache
  - pip install pytest pytest-cov selenium
  - pip install codecov
script:
  - py.test --cov wdom
after_success:
  - codecov
