language: python
python:
  - "3.5"

addons:
  apt:
    packages:
      - google-chrome-stable
      - wget

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d bin
  - export PATH=$HOME/bin:$PATH
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
install:
  - pip install tornado pystache
  - pip install pytest pytest-cov selenium
  - pip install codecov
script:
  - py.test --cov wdom
after_success:
  - codecov
