language: python
python:
  - "3.4.4"
  - "3.5.1"

addons:
  apt:
    packages:
      - xvfb

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - pip install tornado aiohttp
  - pip install selenium nose-parameterized syncer
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4* ]]; then pip install mypy-lang; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5* ]]; then pip install coverage codecov coveralls; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4* ]]; then python run_tests.py; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5* ]]; then coverage run --source wdom run_tests.py; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5* ]]; then codecov -b $TRAVIS_BRANCH && coveralls; fi
