language: python
python:
  - "3.5"

addons:
  apt:
    packages:
      - firefox
      - wget
      - xvfb

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - pip install tornado pystache
  - pip install pytest pytest-cov selenium
  - pip install codecov
script:
  - py.test --cov wdom
after_success:
  - codecov
