language: python
python:
  - "3.4.4"
  - "3.5.1"

addons:
  apt:
    packages:
      - xvfb

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - pip install tox
  - pip install selenium nose_parameterized syncer coverage
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4* ]]; then pip install mypy-lang; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5* ]]; then pip install codecov coveralls; fi
  - pip install .
script:
  - tox -c tox_travis.ini
  - coverage erase
  - coverage run --source wdom wdom/tests/run_tests.py
  - pip install aiohttp
  - coverage run -a --source wdom wdom/tests/run_tests.py
  - coverage report
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5* ]]; then codecov -b $TRAVIS_BRANCH && coveralls; fi
