language: python
python:
  - "3.5"

addons:
  apt:
    packages:
      - chromium-browser
      - chromium-chromedriver
      - libxi6
      - libgconf-2-4
      - wget
      - xvfb

install:
  - pip install tornado pystache
  - pip install pytest pytest-cov selenium
  - pip install codecov
script:
  - xvfb-run py.test --cov wdom
after_success:
  - codecov
