language: python
python:
  - "3.4.4"
  - "3.5.1"

addons:
  apt:
    packages:
      - xvfb

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - pip install tornado aiohttp
  - pip install selenium nose-parametrized syncer
  - [[ $TRAVIS_PYTHON_VERSION == 3.4* ]] && pip install mypy-lang
  - [[ $TRAVIS_PYTHON_VERSION == 3.5* ]] && pip install codecov coveralls; fi
script:
  - [[ $TRAVIS_PYTHON_VERSION == 3.4* ]] && python run_test.py
  - [[ $TRAVIS_PYTHON_VERSION == 3.5* ]] && coverage run --source wdom run_test.py
after_success:
  - [[ $TRAVIS_PYTHON_VERSION == 3.5* ]] && codecov -b $TRAVIS_BRANCH && coveralls
